// SPDX-FileCopyrightText: Copyright 2026 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

#include "input/midi_kit_probe_data.h"

#include <algorithm>
#include <array>
#include <map>
#include <sstream>

namespace Input::MidiInstrument {

namespace {

// All step keys the wizard's drum walkthrough emits, in the order they
// appear in the kit_probe_dialog walkthrough. Steps that don't have a
// corresponding MIDI pad slot (e.g. button_start) are not listed here;
// the derive ignores them when building the TOML.
struct PadDef {
    const char* step;
    const char* toml_key;
    bool optional;
};
const PadDef kDrumPads[] = {
    {"red_pad",         "red",          false},
    {"blue_pad",        "blue",         false},
    {"yellow_pad",      "yellow",       true},
    {"green_pad",       "green",        true},
    {"orange_pad",      "orange",       true},
    {"kick_pedal",      "kick",         false},
    {"kick_pedal_2",    "kick2",        true},
};
const PadDef kProCymbals[] = {
    {"yellow_cymbal",   "yellow_cymbal", true},
    {"orange_cymbal",   "orange_cymbal", true},
    {"blue_cymbal",     "blue_cymbal",   true},
    {"green_cymbal",    "green_cymbal",  true},
};

// Pick the top-N MIDI notes from a step's event list, ranked by peak
// velocity. We allow multiple notes per pad because real e-drum modules
// often send two notes per pad (e.g. snare head vs rim, hi-hat closed
// vs open). The wizard probes one pad at a time, so anything the user
// hit during the red_pad step is by definition "red".
//
// Returns a sorted list of notes. peak_vel is the highest velocity seen
// on that note in this step. count is the number of Note On events with
// that note in this step (mostly informational; not used by the TOML).
struct NoteStats {
    std::uint8_t note;
    std::uint8_t peak_vel;
    int count;
};
std::vector<NoteStats> RankNotesForStep(const MidiStepResult& step,
                                        int max_notes = 4) {
    std::map<std::uint8_t, NoteStats> by_note;
    for (const auto& ev : step.events) {
        if (!ev.on) continue;
        auto& s = by_note[ev.note];
        s.note = ev.note;
        if (ev.velocity > s.peak_vel) s.peak_vel = ev.velocity;
        s.count++;
    }
    std::vector<NoteStats> all;
    all.reserve(by_note.size());
    for (auto& [n, s] : by_note) all.push_back(s);
    std::sort(all.begin(), all.end(),
              [](const NoteStats& a, const NoteStats& b) {
                  // Higher peak velocity wins; ties broken by frequency.
                  if (a.peak_vel != b.peak_vel) return a.peak_vel > b.peak_vel;
                  return a.count > b.count;
              });
    if ((int)all.size() > max_notes) all.resize(max_notes);
    return all;
}

const MidiStepResult* FindStep(const MidiKitProbeData& data, const std::string& key) {
    for (const auto& s : data.results) {
        if (s.key == key && s.captured) return &s;
    }
    return nullptr;
}

void EmitPadMap(std::ostringstream& os, const MidiKitProbeData& data,
                const PadDef& pad) {
    const auto* step = FindStep(data, pad.step);
    if (!step) return;
    const auto notes = RankNotesForStep(*step);
    if (notes.empty()) return;
    os << pad.toml_key << " = [";
    for (std::size_t i = 0; i < notes.size(); ++i) {
        if (i) os << ", ";
        os << static_cast<int>(notes[i].note);
    }
    os << "]\n";
}

void EmitVelocityScale(std::ostringstream& os, const MidiKitProbeData& data,
                       const PadDef& pad) {
    const auto* step = FindStep(data, pad.step);
    if (!step) return;
    const auto notes = RankNotesForStep(*step);
    if (notes.empty()) return;
    // Use the dominant note's range. lo defaults to 1 (any hit at all
    // counts as a press); hi is the peak observed velocity. The
    // runtime maps [lo, hi] linearly onto [0, 0x7F] so a worn-pad
    // module with a max-velocity of e.g. 90 isn't clipped to half-power
    // in game.
    const int lo = 1;
    const int hi = notes.front().peak_vel;
    if (hi <= lo) return;
    os << "\"" << pad.toml_key << "\" = { lo = " << lo << ", hi = " << hi
       << " }\n";
}

}  // namespace

std::string DeriveMidiKitToml(const MidiKitProbeData& data) {
    std::ostringstream os;
    os << "# Generated by KitProbeDialog (MIDI). Picked up at next launch.\n\n";
    os << "schema       = \"shadps4-midi-instrument/v1\"\n";
    os << "name         = \"" << data.device_name << "\"\n";
    os << "source       = \"midi\"\n";
    os << "port_id      = \"" << data.port_id << "\"\n";
    os << "device_class = \"drum\"\n";

    const bool is_pro = (data.device_type == MidiDeviceType::ProDrum);
    os << "device_subclass = \""
       << (is_pro ? "pro_drum" : "drum") << "\"\n\n";

    // The Note → pad map. Multiple notes per pad are kept (some modules
    // expose snare head vs rim as separate notes, or hi-hat closed vs
    // open). The runtime ORs all listed notes into the same pad slot.
    os << "[midi_pad_map]\n";
    for (const auto& pad : kDrumPads) EmitPadMap(os, data, pad);
    if (is_pro) {
        for (const auto& pad : kProCymbals) EmitPadMap(os, data, pad);
    }
    os << "\n";

    // Per-pad velocity scaling — derived from the peak velocity observed
    // during each step. Compensates for worn pads / lower-trigger-zone
    // modules so a moderately-hard hit reaches RB4's max velocity.
    bool any_scale = false;
    std::ostringstream scale_buf;
    for (const auto& pad : kDrumPads) {
        const std::size_t before = scale_buf.tellp();
        EmitVelocityScale(scale_buf, data, pad);
        if (static_cast<std::size_t>(scale_buf.tellp()) != before) any_scale = true;
    }
    if (is_pro) {
        for (const auto& pad : kProCymbals) {
            const std::size_t before = scale_buf.tellp();
            EmitVelocityScale(scale_buf, data, pad);
            if (static_cast<std::size_t>(scale_buf.tellp()) != before) any_scale = true;
        }
    }
    if (any_scale) {
        os << "[velocity_scaling]\n" << scale_buf.str();
    }

    return os.str();
}

}  // namespace Input::MidiInstrument
